// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_svc.proto

#include "login_svc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace sproto {
class UserLoginReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UserLoginReq>
      _instance;
} _UserLoginReq_default_instance_;
class GetSessionReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetSessionReq>
      _instance;
} _GetSessionReq_default_instance_;
class OnLoginDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<OnLogin>
      _instance;
} _OnLogin_default_instance_;
}  // namespace sproto
namespace protobuf_login_5fsvc_2eproto {
static void InitDefaultsUserLoginReq() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sproto::_UserLoginReq_default_instance_;
    new (ptr) ::sproto::UserLoginReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sproto::UserLoginReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_UserLoginReq =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUserLoginReq}, {}};

static void InitDefaultsGetSessionReq() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sproto::_GetSessionReq_default_instance_;
    new (ptr) ::sproto::GetSessionReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sproto::GetSessionReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetSessionReq =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetSessionReq}, {}};

static void InitDefaultsOnLogin() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sproto::_OnLogin_default_instance_;
    new (ptr) ::sproto::OnLogin();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sproto::OnLogin::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_OnLogin =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsOnLogin}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_UserLoginReq.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GetSessionReq.base);
  ::google::protobuf::internal::InitSCC(&scc_info_OnLogin.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::UserLoginReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::UserLoginReq, gateaddr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::UserLoginReq, gateclient_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::UserLoginReq, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::UserLoginReq, password_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::GetSessionReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::GetSessionReq, username_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::OnLogin, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::OnLogin, broadcast_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::OnLogin, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::OnLogin, namehash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::OnLogin, owneraddr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::OnLogin, token_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::OnLogin, gateaddr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::sproto::OnLogin, gateclient_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sproto::UserLoginReq)},
  { 9, -1, sizeof(::sproto::GetSessionReq)},
  { 15, -1, sizeof(::sproto::OnLogin)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::sproto::_UserLoginReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::sproto::_GetSessionReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::sproto::_OnLogin_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "login_svc.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017login_svc.proto\022\006sproto\"T\n\014UserLoginRe"
      "q\022\020\n\010GateAddr\030\001 \001(\t\022\022\n\nGateClient\030\002 \001(\004\022"
      "\014\n\004Name\030\003 \001(\t\022\020\n\010Password\030\004 \001(\t\"!\n\rGetSe"
      "ssionReq\022\020\n\010UserName\030\001 \001(\t\"\204\001\n\007OnLogin\022\021"
      "\n\tBroadcast\030\001 \001(\010\022\014\n\004Name\030\002 \001(\t\022\020\n\010NameH"
      "ash\030\003 \001(\r\022\021\n\tOwnerAddr\030\004 \001(\t\022\r\n\005Token\030\005 "
      "\001(\t\022\020\n\010GateAddr\030\006 \001(\t\022\022\n\nGateClient\030\007 \001("
      "\004b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 289);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "login_svc.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_login_5fsvc_2eproto
namespace sproto {

// ===================================================================

void UserLoginReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UserLoginReq::kGateAddrFieldNumber;
const int UserLoginReq::kGateClientFieldNumber;
const int UserLoginReq::kNameFieldNumber;
const int UserLoginReq::kPasswordFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UserLoginReq::UserLoginReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_login_5fsvc_2eproto::scc_info_UserLoginReq.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:sproto.UserLoginReq)
}
UserLoginReq::UserLoginReq(const UserLoginReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  gateaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.gateaddr().size() > 0) {
    gateaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gateaddr_);
  }
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.password().size() > 0) {
    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  gateclient_ = from.gateclient_;
  // @@protoc_insertion_point(copy_constructor:sproto.UserLoginReq)
}

void UserLoginReq::SharedCtor() {
  gateaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gateclient_ = GOOGLE_ULONGLONG(0);
}

UserLoginReq::~UserLoginReq() {
  // @@protoc_insertion_point(destructor:sproto.UserLoginReq)
  SharedDtor();
}

void UserLoginReq::SharedDtor() {
  gateaddr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UserLoginReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UserLoginReq::descriptor() {
  ::protobuf_login_5fsvc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_5fsvc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UserLoginReq& UserLoginReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_login_5fsvc_2eproto::scc_info_UserLoginReq.base);
  return *internal_default_instance();
}


void UserLoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:sproto.UserLoginReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  gateaddr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gateclient_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool UserLoginReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sproto.UserLoginReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string GateAddr = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_gateaddr()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->gateaddr().data(), static_cast<int>(this->gateaddr().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sproto.UserLoginReq.GateAddr"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 GateClient = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &gateclient_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Name = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sproto.UserLoginReq.Name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Password = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), static_cast<int>(this->password().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sproto.UserLoginReq.Password"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sproto.UserLoginReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sproto.UserLoginReq)
  return false;
#undef DO_
}

void UserLoginReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sproto.UserLoginReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string GateAddr = 1;
  if (this->gateaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->gateaddr().data(), static_cast<int>(this->gateaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.UserLoginReq.GateAddr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->gateaddr(), output);
  }

  // uint64 GateClient = 2;
  if (this->gateclient() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->gateclient(), output);
  }

  // string Name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.UserLoginReq.Name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->name(), output);
  }

  // string Password = 4;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.UserLoginReq.Password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->password(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:sproto.UserLoginReq)
}

::google::protobuf::uint8* UserLoginReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:sproto.UserLoginReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string GateAddr = 1;
  if (this->gateaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->gateaddr().data(), static_cast<int>(this->gateaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.UserLoginReq.GateAddr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->gateaddr(), target);
  }

  // uint64 GateClient = 2;
  if (this->gateclient() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->gateclient(), target);
  }

  // string Name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.UserLoginReq.Name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // string Password = 4;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.UserLoginReq.Password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->password(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sproto.UserLoginReq)
  return target;
}

size_t UserLoginReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sproto.UserLoginReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string GateAddr = 1;
  if (this->gateaddr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->gateaddr());
  }

  // string Name = 3;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string Password = 4;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  // uint64 GateClient = 2;
  if (this->gateclient() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->gateclient());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UserLoginReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sproto.UserLoginReq)
  GOOGLE_DCHECK_NE(&from, this);
  const UserLoginReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UserLoginReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sproto.UserLoginReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sproto.UserLoginReq)
    MergeFrom(*source);
  }
}

void UserLoginReq::MergeFrom(const UserLoginReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sproto.UserLoginReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.gateaddr().size() > 0) {

    gateaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gateaddr_);
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  if (from.gateclient() != 0) {
    set_gateclient(from.gateclient());
  }
}

void UserLoginReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sproto.UserLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserLoginReq::CopyFrom(const UserLoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sproto.UserLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserLoginReq::IsInitialized() const {
  return true;
}

void UserLoginReq::Swap(UserLoginReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UserLoginReq::InternalSwap(UserLoginReq* other) {
  using std::swap;
  gateaddr_.Swap(&other->gateaddr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  password_.Swap(&other->password_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(gateclient_, other->gateclient_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UserLoginReq::GetMetadata() const {
  protobuf_login_5fsvc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_5fsvc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetSessionReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetSessionReq::kUserNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetSessionReq::GetSessionReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_login_5fsvc_2eproto::scc_info_GetSessionReq.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:sproto.GetSessionReq)
}
GetSessionReq::GetSessionReq(const GetSessionReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.username().size() > 0) {
    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  // @@protoc_insertion_point(copy_constructor:sproto.GetSessionReq)
}

void GetSessionReq::SharedCtor() {
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GetSessionReq::~GetSessionReq() {
  // @@protoc_insertion_point(destructor:sproto.GetSessionReq)
  SharedDtor();
}

void GetSessionReq::SharedDtor() {
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GetSessionReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetSessionReq::descriptor() {
  ::protobuf_login_5fsvc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_5fsvc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetSessionReq& GetSessionReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_login_5fsvc_2eproto::scc_info_GetSessionReq.base);
  return *internal_default_instance();
}


void GetSessionReq::Clear() {
// @@protoc_insertion_point(message_clear_start:sproto.GetSessionReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool GetSessionReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sproto.GetSessionReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string UserName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->username().data(), static_cast<int>(this->username().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sproto.GetSessionReq.UserName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sproto.GetSessionReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sproto.GetSessionReq)
  return false;
#undef DO_
}

void GetSessionReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sproto.GetSessionReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string UserName = 1;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), static_cast<int>(this->username().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.GetSessionReq.UserName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->username(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:sproto.GetSessionReq)
}

::google::protobuf::uint8* GetSessionReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:sproto.GetSessionReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string UserName = 1;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), static_cast<int>(this->username().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.GetSessionReq.UserName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->username(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sproto.GetSessionReq)
  return target;
}

size_t GetSessionReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sproto.GetSessionReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string UserName = 1;
  if (this->username().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetSessionReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sproto.GetSessionReq)
  GOOGLE_DCHECK_NE(&from, this);
  const GetSessionReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetSessionReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sproto.GetSessionReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sproto.GetSessionReq)
    MergeFrom(*source);
  }
}

void GetSessionReq::MergeFrom(const GetSessionReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sproto.GetSessionReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.username().size() > 0) {

    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
}

void GetSessionReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sproto.GetSessionReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetSessionReq::CopyFrom(const GetSessionReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sproto.GetSessionReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetSessionReq::IsInitialized() const {
  return true;
}

void GetSessionReq::Swap(GetSessionReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetSessionReq::InternalSwap(GetSessionReq* other) {
  using std::swap;
  username_.Swap(&other->username_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetSessionReq::GetMetadata() const {
  protobuf_login_5fsvc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_5fsvc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void OnLogin::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OnLogin::kBroadcastFieldNumber;
const int OnLogin::kNameFieldNumber;
const int OnLogin::kNameHashFieldNumber;
const int OnLogin::kOwnerAddrFieldNumber;
const int OnLogin::kTokenFieldNumber;
const int OnLogin::kGateAddrFieldNumber;
const int OnLogin::kGateClientFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OnLogin::OnLogin()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_login_5fsvc_2eproto::scc_info_OnLogin.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:sproto.OnLogin)
}
OnLogin::OnLogin(const OnLogin& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  owneraddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.owneraddr().size() > 0) {
    owneraddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.owneraddr_);
  }
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.token().size() > 0) {
    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  gateaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.gateaddr().size() > 0) {
    gateaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gateaddr_);
  }
  ::memcpy(&broadcast_, &from.broadcast_,
    static_cast<size_t>(reinterpret_cast<char*>(&gateclient_) -
    reinterpret_cast<char*>(&broadcast_)) + sizeof(gateclient_));
  // @@protoc_insertion_point(copy_constructor:sproto.OnLogin)
}

void OnLogin::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  owneraddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gateaddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&broadcast_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&gateclient_) -
      reinterpret_cast<char*>(&broadcast_)) + sizeof(gateclient_));
}

OnLogin::~OnLogin() {
  // @@protoc_insertion_point(destructor:sproto.OnLogin)
  SharedDtor();
}

void OnLogin::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  owneraddr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gateaddr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void OnLogin::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* OnLogin::descriptor() {
  ::protobuf_login_5fsvc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_5fsvc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OnLogin& OnLogin::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_login_5fsvc_2eproto::scc_info_OnLogin.base);
  return *internal_default_instance();
}


void OnLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:sproto.OnLogin)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  owneraddr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gateaddr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&broadcast_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&gateclient_) -
      reinterpret_cast<char*>(&broadcast_)) + sizeof(gateclient_));
  _internal_metadata_.Clear();
}

bool OnLogin::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sproto.OnLogin)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool Broadcast = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &broadcast_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sproto.OnLogin.Name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 NameHash = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &namehash_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string OwnerAddr = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_owneraddr()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->owneraddr().data(), static_cast<int>(this->owneraddr().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sproto.OnLogin.OwnerAddr"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Token = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->token().data(), static_cast<int>(this->token().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sproto.OnLogin.Token"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string GateAddr = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_gateaddr()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->gateaddr().data(), static_cast<int>(this->gateaddr().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "sproto.OnLogin.GateAddr"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 GateClient = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &gateclient_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sproto.OnLogin)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sproto.OnLogin)
  return false;
#undef DO_
}

void OnLogin::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sproto.OnLogin)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool Broadcast = 1;
  if (this->broadcast() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->broadcast(), output);
  }

  // string Name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.OnLogin.Name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // uint32 NameHash = 3;
  if (this->namehash() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->namehash(), output);
  }

  // string OwnerAddr = 4;
  if (this->owneraddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->owneraddr().data(), static_cast<int>(this->owneraddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.OnLogin.OwnerAddr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->owneraddr(), output);
  }

  // string Token = 5;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), static_cast<int>(this->token().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.OnLogin.Token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->token(), output);
  }

  // string GateAddr = 6;
  if (this->gateaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->gateaddr().data(), static_cast<int>(this->gateaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.OnLogin.GateAddr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->gateaddr(), output);
  }

  // uint64 GateClient = 7;
  if (this->gateclient() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(7, this->gateclient(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:sproto.OnLogin)
}

::google::protobuf::uint8* OnLogin::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:sproto.OnLogin)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool Broadcast = 1;
  if (this->broadcast() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->broadcast(), target);
  }

  // string Name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.OnLogin.Name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // uint32 NameHash = 3;
  if (this->namehash() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->namehash(), target);
  }

  // string OwnerAddr = 4;
  if (this->owneraddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->owneraddr().data(), static_cast<int>(this->owneraddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.OnLogin.OwnerAddr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->owneraddr(), target);
  }

  // string Token = 5;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), static_cast<int>(this->token().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.OnLogin.Token");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->token(), target);
  }

  // string GateAddr = 6;
  if (this->gateaddr().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->gateaddr().data(), static_cast<int>(this->gateaddr().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "sproto.OnLogin.GateAddr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->gateaddr(), target);
  }

  // uint64 GateClient = 7;
  if (this->gateclient() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(7, this->gateclient(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sproto.OnLogin)
  return target;
}

size_t OnLogin::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sproto.OnLogin)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string Name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string OwnerAddr = 4;
  if (this->owneraddr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->owneraddr());
  }

  // string Token = 5;
  if (this->token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->token());
  }

  // string GateAddr = 6;
  if (this->gateaddr().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->gateaddr());
  }

  // bool Broadcast = 1;
  if (this->broadcast() != 0) {
    total_size += 1 + 1;
  }

  // uint32 NameHash = 3;
  if (this->namehash() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->namehash());
  }

  // uint64 GateClient = 7;
  if (this->gateclient() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->gateclient());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OnLogin::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sproto.OnLogin)
  GOOGLE_DCHECK_NE(&from, this);
  const OnLogin* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OnLogin>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sproto.OnLogin)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sproto.OnLogin)
    MergeFrom(*source);
  }
}

void OnLogin::MergeFrom(const OnLogin& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sproto.OnLogin)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.owneraddr().size() > 0) {

    owneraddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.owneraddr_);
  }
  if (from.token().size() > 0) {

    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  if (from.gateaddr().size() > 0) {

    gateaddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gateaddr_);
  }
  if (from.broadcast() != 0) {
    set_broadcast(from.broadcast());
  }
  if (from.namehash() != 0) {
    set_namehash(from.namehash());
  }
  if (from.gateclient() != 0) {
    set_gateclient(from.gateclient());
  }
}

void OnLogin::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sproto.OnLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OnLogin::CopyFrom(const OnLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sproto.OnLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OnLogin::IsInitialized() const {
  return true;
}

void OnLogin::Swap(OnLogin* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OnLogin::InternalSwap(OnLogin* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  owneraddr_.Swap(&other->owneraddr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  token_.Swap(&other->token_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  gateaddr_.Swap(&other->gateaddr_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(broadcast_, other->broadcast_);
  swap(namehash_, other->namehash_);
  swap(gateclient_, other->gateclient_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata OnLogin::GetMetadata() const {
  protobuf_login_5fsvc_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_login_5fsvc_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sproto
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::sproto::UserLoginReq* Arena::CreateMaybeMessage< ::sproto::UserLoginReq >(Arena* arena) {
  return Arena::CreateInternal< ::sproto::UserLoginReq >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::sproto::GetSessionReq* Arena::CreateMaybeMessage< ::sproto::GetSessionReq >(Arena* arena) {
  return Arena::CreateInternal< ::sproto::GetSessionReq >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::sproto::OnLogin* Arena::CreateMaybeMessage< ::sproto::OnLogin >(Arena* arena) {
  return Arena::CreateInternal< ::sproto::OnLogin >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
