// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

/*
Package cproto is a generated protocol buffer package.

It is generated from these files:
	proto.proto

It has these top-level messages:
	NewUserReq
	NewUserRes
	LoginReq
	LoginRes
*/
package cproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewUserReq struct {
	Name     string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *NewUserReq) Reset()                    { *m = NewUserReq{} }
func (m *NewUserReq) String() string            { return proto.CompactTextString(m) }
func (*NewUserReq) ProtoMessage()               {}
func (*NewUserReq) Descriptor() ([]byte, []int) { return fileDescriptor_proto, []int{0} }

func (m *NewUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type NewUserRes struct {
	Ret int32  `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
}

func (m *NewUserRes) Reset()                    { *m = NewUserRes{} }
func (m *NewUserRes) String() string            { return proto.CompactTextString(m) }
func (*NewUserRes) ProtoMessage()               {}
func (*NewUserRes) Descriptor() ([]byte, []int) { return fileDescriptor_proto, []int{1} }

func (m *NewUserRes) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *NewUserRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginReq struct {
	Name     string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor_proto, []int{2} }

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRes struct {
	Ret   int32  `protobuf:"varint,1,opt,name=Ret" json:"Ret,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
	Token string `protobuf:"bytes,3,opt,name=Token" json:"Token,omitempty"`
}

func (m *LoginRes) Reset()                    { *m = LoginRes{} }
func (m *LoginRes) String() string            { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()               {}
func (*LoginRes) Descriptor() ([]byte, []int) { return fileDescriptor_proto, []int{3} }

func (m *LoginRes) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *LoginRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUserReq)(nil), "cproto.NewUserReq")
	proto.RegisterType((*NewUserRes)(nil), "cproto.NewUserRes")
	proto.RegisterType((*LoginReq)(nil), "cproto.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "cproto.LoginRes")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_proto) }

var fileDescriptor_proto = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x03, 0x93, 0x42, 0x6c, 0xc9, 0x60, 0x5a, 0xc9, 0x86, 0x8b, 0xcb, 0x2f, 0xb5, 0x3c,
	0xb4, 0x38, 0xb5, 0x28, 0x28, 0xb5, 0x50, 0x48, 0x88, 0x8b, 0xc5, 0x2f, 0x31, 0x37, 0x55, 0x82,
	0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x92, 0xe2, 0xe2, 0x08, 0x48, 0x2c, 0x2e, 0x2e,
	0xcf, 0x2f, 0x4a, 0x91, 0x60, 0x02, 0x8b, 0xc3, 0xf9, 0x4a, 0x06, 0x48, 0xba, 0x8b, 0x85, 0x04,
	0xb8, 0x98, 0x83, 0x52, 0x4b, 0xc0, 0x9a, 0x59, 0x83, 0x40, 0x4c, 0x90, 0x88, 0x6f, 0x71, 0x3a,
	0x54, 0x1b, 0x88, 0xa9, 0x64, 0xc5, 0xc5, 0xe1, 0x93, 0x9f, 0x9e, 0x99, 0x47, 0x8e, 0x6d, 0x2e,
	0x70, 0xbd, 0x44, 0xd9, 0x25, 0x24, 0xc2, 0xc5, 0x1a, 0x92, 0x9f, 0x9d, 0x9a, 0x27, 0xc1, 0x0c,
	0x16, 0x83, 0x70, 0x92, 0xd8, 0xc0, 0x1e, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x1c,
	0xaa, 0x4c, 0x0f, 0x01, 0x00, 0x00,
}
