// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic_svc.proto

/*
Package sproto is a generated protocol buffer package.

It is generated from these files:
	logic_svc.proto

It has these top-level messages:
	Login
*/
package sproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Login struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=Addr" json:"Addr,omitempty"`
	Sex  int32  `protobuf:"varint,4,opt,name=Sex" json:"Sex,omitempty"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor_logic_svc, []int{0} }

func (m *Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Login) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Login) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func init() {
	proto.RegisterType((*Login)(nil), "sproto.Login")
}

func init() { proto.RegisterFile("logic_svc.proto", fileDescriptor_logic_svc) }

var fileDescriptor_logic_svc = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xc9, 0x4f, 0xcf,
	0x4c, 0x8e, 0x2f, 0x2e, 0x4b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x06, 0xd3,
	0x4a, 0x8e, 0x5c, 0xac, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x42, 0x42, 0x5c, 0x2c, 0x7e, 0x89, 0xb9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0xcc, 0x31, 0x25, 0xa5, 0x48,
	0x82, 0x09, 0x22, 0x06, 0x62, 0x0b, 0x09, 0x70, 0x31, 0x07, 0xa7, 0x56, 0x48, 0xb0, 0x28, 0x30,
	0x6a, 0xb0, 0x06, 0x81, 0x98, 0x49, 0x6c, 0x60, 0x93, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xcd, 0x6f, 0x4f, 0xac, 0x64, 0x00, 0x00, 0x00,
}
