// Code generated by protoc-gen-go. DO NOT EDIT.
// source: public.proto

/*
Package sproto is a generated protocol buffer package.

It is generated from these files:
	public.proto

It has these top-level messages:
	Broadcast
*/
package sproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Broadcast struct {
}

func (m *Broadcast) Reset()                    { *m = Broadcast{} }
func (m *Broadcast) String() string            { return proto.CompactTextString(m) }
func (*Broadcast) ProtoMessage()               {}
func (*Broadcast) Descriptor() ([]byte, []int) { return fileDescriptor_public, []int{0} }

func init() {
	proto.RegisterType((*Broadcast)(nil), "sproto.Broadcast")
}

func init() { proto.RegisterFile("public.proto", fileDescriptor_public) }

var fileDescriptor_public = []byte{
	// 61 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x28, 0x4d, 0xca,
	0xc9, 0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x06, 0xd3, 0x4a, 0xdc, 0x5c,
	0x9c, 0x4e, 0x45, 0xf9, 0x89, 0x29, 0xc9, 0x89, 0xc5, 0x25, 0x49, 0x6c, 0x60, 0x31, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0x3c, 0xb6, 0x46, 0x2b, 0x00, 0x00, 0x00,
}
